spring.application.name=NativeVsSpecification
#Postgresql configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/jet02
spring.datasource.username=myuser
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update